-- ============================================================================
-- VIP CALLS — recurring trainer-set call blocks (e.g. Blake's daily
-- accountability calls). Run once in the Supabase SQL editor.
--
-- Dark to anon and authenticated from creation — every read and write goes
-- through the trainer door (netlify/functions/trainer.js) or, for the
-- offer page's public availability check, through consult-availability.js
-- with the service key. No client-facing surface ever queries this table
-- directly with the public key: a client's own read goes through the new
-- session-scoped myVipCalls op, hard-scoped server-side to their own
-- client_code, same pattern as spendCallCredit.
--
-- SHAPE
--   client_code       the client this recurring block belongs to
--   weekdays          1=Mon..7=Sun — the same numbering movement_prefs.walks
--                      already uses app-wide
--   time_local        wall-clock start time, e.g. "09:30" — NOT pre-converted
--   tz                IANA zone the time is in; defaults Eastern
--   duration_minutes  length of each occurrence
--   start_date/end_date   inclusive range the recurrence runs across
--   notes             trainer-only, never client-facing
--   active            soft on/off — pausing a block never deletes its history
--
-- Stored as a RULE (weekdays + local time + zone), not pre-computed
-- timestamps, so a block that spans a DST change is still correct: whatever
-- reads this expands it to real occurrences at query time, converting
-- time_local+tz to UTC per calendar date rather than baking in one fixed
-- offset.
-- ============================================================================

begin;

create table if not exists public.vip_calls (
  id                bigint generated by default as identity primary key,
  client_code       text not null,
  weekdays          smallint[] not null,
  time_local        text not null,
  tz                text not null default 'America/New_York',
  duration_minutes  int not null,
  start_date        date not null,
  end_date          date not null,
  notes             text,
  active            boolean not null default true,
  created_at        timestamptz not null default now()
);

create index if not exists vip_calls_active_range_idx
  on public.vip_calls (active, start_date, end_date);
create index if not exists vip_calls_client_code_idx
  on public.vip_calls (client_code);

comment on table public.vip_calls is
  'Recurring trainer-set call blocks. Dark to anon/authenticated — reads and '
  'writes only through the trainer door or the service-key availability check.';
comment on column public.vip_calls.weekdays is '1=Mon..7=Sun';
comment on column public.vip_calls.time_local is
  'Wall-clock "HH:MM" in the tz column — never pre-converted to UTC.';

alter table public.vip_calls enable row level security;
revoke all on public.vip_calls from anon;
revoke all on public.vip_calls from authenticated;

notify pgrst, 'reload schema';

commit;
-- ============================================================================
