-- ============================================================================
-- BLOCK DISPLAY NAMES — how a calendar block is PRESENTED, never what it is.
-- Run once in the Supabase SQL editor.
--
-- Approved by ruling (COORDINATION, 20 Aug): "display labels only, nothing
-- else persists there." Ruling 3 of the same set puts the per-block
-- expand/time-true choice here too ("stored in the new table"), so this
-- table carries exactly two presentation facts and nothing else:
--
--   display_name   what the block's title READS as on the calendar
--   fit_mode       whether the block grows to fit its title or stays time-true
--
-- NOTHING ABOUT THE RECORD ITSELF EVER LANDS HERE. The food row, its macros,
-- its eat_time and the thread record keep the real name and the real numbers.
-- A rename is a label on a window, not a change to what is behind it. If a
-- future session wants to store content here, it wants a different table.
--
-- DARK FROM BIRTH (COORDINATION, 20 Aug: "RLS from birth: client surfaces get
-- no read of trainer labels they should not see"). Same posture as vip_calls
-- and call_notes: RLS on with NO policies, and all privileges revoked from
-- anon and authenticated. That is deny-all twice over — a client surface
-- holding the public key cannot read one row of this table, so a label Yusuf
-- writes on his own calendar can never surface in a client's app.
--
-- Every read and write therefore goes through the trainer door
-- (netlify/functions/trainer.js) with the service key, which already scopes
-- by trainer session. There is no client-facing op and none should be added:
-- these are the trainer's private labels for his own week.
--
-- KEYING
--   owner_code   whose calendar the label belongs to — owner_code, NOT
--                client_code, matching calendar_blocks (see
--                JV_CLIENT_TABLE_COL in index.html, which this table joins).
--   target_kind  'food' | 'wo' | 'cal' | 'appt' — which renderer owns it
--   target_key   the SAME key string the renderer already computes, so there
--                is one key vocabulary and not a second one to keep in step:
--                  food log            food:<food_logs.id>
--                  workout log         wo:<workout_logs.id>
--                  calendar occurrence cal:<calendar_blocks.id>|<dateStr>
--                  appointment         appt:<_wkApptKey(r)>
--                Text, not bigint: an occurrence key carries a date and an
--                appointment key carries its own kind prefix, so no numeric
--                column can hold all four shapes.
--
-- A LABEL OUTLIVES NOTHING. There is no foreign key: the four target kinds
-- live in four different tables and one of them (a calendar occurrence) has
-- no row of its own at all until it is excepted. A label whose target is gone
-- is simply never read again; jvRemoveClient clears them by owner_code.
-- ============================================================================

begin;

create table if not exists public.block_display_names (
  id            bigint generated by default as identity primary key,
  owner_code    text not null,
  target_kind   text not null,
  target_key    text not null,
  display_name  text,
  fit_mode      text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint block_display_names_kind_ck
    check (target_kind in ('food','wo','cal','appt')),
  -- null = "he has not chosen", which is NOT the same as choosing time-true.
  -- The renderer's default is time-true; this column only ever records a
  -- deliberate choice, so a later change of default does not silently
  -- rewrite every block he never touched.
  constraint block_display_names_fit_ck
    check (fit_mode is null or fit_mode in ('fit','time'))
);

-- One row per block per owner. The upsert path relies on this: a second
-- rename of the same block must overwrite, never accumulate a second row
-- that a read would then have to pick between.
create unique index if not exists block_display_names_target_uq
  on public.block_display_names (owner_code, target_key);

create index if not exists block_display_names_owner_idx
  on public.block_display_names (owner_code);

comment on table public.block_display_names is
  'Presentation only: what a calendar block READS as, and whether it grows to '
  'fit its title. Never the record itself — the food/workout row keeps the '
  'real name and macros. Dark to anon/authenticated; trainer door only.';
comment on column public.block_display_names.target_key is
  'The renderer''s own key string: food:<id> | wo:<id> | cal:<id>|<dateStr> | appt:<apptKey>';
comment on column public.block_display_names.fit_mode is
  'null = never chosen (renderer default, time-true). fit = grow to fit title. time = stay time-true.';

alter table public.block_display_names enable row level security;
revoke all on public.block_display_names from anon;
revoke all on public.block_display_names from authenticated;

notify pgrst, 'reload schema';

commit;

-- ROLLBACK, in one paste, if this needs to go away:
--   begin;
--   drop table if exists public.block_display_names;
--   notify pgrst, 'reload schema';
--   commit;
-- ============================================================================
