-- ============================================================================
-- CALL INVITES — the trainer invites a client to book a check-in call, and
-- asks them a short list of questions they answer while they pick the time.
-- Run once in the Supabase SQL editor.
--
-- Dark to anon and authenticated from creation, same posture as vip_calls and
-- call_notes: RLS on with NO policies and every privilege revoked, so the only
-- way in is the trainer door (netlify/functions/trainer.js) with the service
-- key. The client's own read and their own answer go through the two
-- session-scoped ops myInvite / myInviteAnswer, hard-scoped server-side to
-- claims.client_code, never to anything the caller can supply.
--
-- SHAPE
--   client_code   who was invited. One pending invite per client is the rule
--                 the door enforces, not a constraint here: a second invite
--                 supersedes the first rather than stacking two cards on her
--                 screen.
--   questions     jsonb ARRAY OF STRINGS, stored VERBATIM in the order he
--                 said them. Law 2 of the parse: never reworded, merged, or
--                 split differently. Zero questions is valid (law 3) and is
--                 stored as [], never null, so nothing downstream has to tell
--                 "he asked nothing" from "the column did not load".
--   answers       jsonb array of strings, hers, positional against questions.
--                 Null until she answers. Hers and only hers — this column is
--                 never written by the trainer door.
--   booking_id    the booking she picked, filled in the same write as answers.
--   status        'pending' -> 'answered'. 'cancelled' exists so an invite can
--                 be withdrawn without deleting what she already wrote.
--   created_by    the trainer's client_code, off the signed session.
--
-- WHY THE ANSWERS ARE NOT CALL NOTES. They are also written into the call's
-- notes thread, which is what surfaces them in the pre-call debrief — but the
-- thread is prose either of them can add to and delete from, and the invite is
-- a record of a specific question asked and a specific answer given. Losing
-- the pairing to a deleted note would lose the thing the invite is for.
--
-- JV_CLIENT_TABLES in index.html gains 'call_invites' in the same breath this
-- table is created, exactly as vip_calls and call_notes did. A client-keyed
-- table that is not in that list leaves orphaned rows behind forever.
-- ============================================================================

begin;

create table if not exists public.call_invites (
  id           bigint generated by default as identity primary key,
  client_code  text not null,
  created_by   text,
  questions    jsonb not null default '[]'::jsonb,
  answers      jsonb,
  booking_id   bigint,
  status       text not null default 'pending',
  created_at   timestamptz not null default now(),
  answered_at  timestamptz
);

create index if not exists call_invites_client_status_idx
  on public.call_invites (client_code, status, created_at desc);

comment on table public.call_invites is
  'Trainer-issued invitations to book a check-in call, with the questions the '
  'client answers while booking. Dark to anon/authenticated — door only.';
comment on column public.call_invites.questions is
  'jsonb array of strings, VERBATIM and in order. [] is valid and means he '
  'asked nothing.';
comment on column public.call_invites.answers is
  'jsonb array of strings, positional against questions. The client''s own '
  'words, written only through the session-scoped myInviteAnswer op.';

alter table public.call_invites enable row level security;
revoke all on public.call_invites from anon;
revoke all on public.call_invites from authenticated;

notify pgrst, 'reload schema';

commit;
-- ============================================================================
