-- ============================================================================
-- THE CLIENT FILE — a table of its own.
--
-- NOT REQUIRED FOR THE SHELF TO WORK. The Client File ships today on
-- client_notes, as [FILE] rows carrying JSON, for one reason: this lane has no
-- DDL. The service_role key lives in Netlify's environment, PostgREST cannot
-- CREATE TABLE with any key at all, and the standing law is that Yusuf never
-- runs SQL. So the choice was a shelf on an existing table or no shelf, and the
-- shelf shipped.
--
-- This file is the promotion, recorded now so it is not re-derived later. Run
-- it when a Supabase access token exists — the same blocker the restore drill
-- sits behind. NOTHING IN index.html HAS TO CHANGE when it lands except the
-- bodies of cfLoad and cfSave: they are the only two functions that touch
-- storage, and every other caller goes through them.
--
-- WHY client_notes WAS THE HONEST INTERIM, not merely the convenient one:
--   · it is already the per-client log both trainer surfaces read;
--   · [MEMORY], [Jarvis] and [COACHING] rows have carried structured payloads
--     in its `note` column for months — this is that convention, not a new one;
--   · it is in JV_CLIENT_TABLES, so a deleted client takes their file with them.
--
-- THAT LAST POINT IS THE TRAP IN THIS FILE. A NEW table is NOT in
-- JV_CLIENT_TABLES. Adding the table without adding it to that list leaves a
-- removed client's file behind forever — CLAUDE.md names this landmine by name.
-- Step 4 below is not optional and is not SQL.
-- ============================================================================

begin;

-- ---- 1. THE TABLE ---------------------------------------------------------
-- ONE ROW PER SAVE, never one row per client. The history is the point: his
-- law is that any field change produces a fresh draft, so something has to be
-- able to say which field moved and when. A row per save answers that without
-- a second table and without an audit trigger.
create table if not exists client_files (
  id           bigint generated by default as identity primary key,
  client_code  text        not null,
  schema       integer     not null default 1,
  -- His own heading block, above field 1, kept verbatim.
  title        text        not null default '',
  -- The ten fields, each holding his words exactly as pasted. TEXT and not
  -- jsonb: these are prose, they are read back out verbatim, and a json type
  -- would invite something to normalise whitespace inside them.
  goal               text,
  why_words          text,
  push_points        text,
  knowledge_base     text,
  personal_details   text,
  tracked_progress   text,
  relationship_state text,
  red_lines          text,
  wins_record        text,
  last_touch         text,
  -- The headings as he wrote them ("TRACKED PROGRESS (pointer)"), so a file
  -- writes back byte-exact, and the order they appeared in.
  headings     jsonb       not null default '{}'::jsonb,
  field_order  jsonb       not null default '[]'::jsonb,
  created_at   timestamptz not null default now()
);

-- Newest-first per client is the only read this table has.
create index if not exists client_files_code_created_idx
  on client_files (client_code, created_at desc);

-- ---- 2. LOCK IT TO THE TRAINER DOOR ---------------------------------------
-- A Client File is the coach's private read on a person: their red lines, what
-- pushes them, what he must not start. It is strictly more sensitive than
-- client_notes, whose private column has been service-role only since 20 Aug.
-- The anon key gets NOTHING here — not select, not insert.
alter table client_files enable row level security;
revoke all on table client_files from anon;
revoke all on table client_files from authenticated;
-- service_role bypasses RLS, which is how netlify/functions/trainer.js reads it.

-- ---- 3. PROVE IT BEFORE COMMITTING ----------------------------------------
-- Same shape as every other migration here: assert, then decide.
do $$
begin
  if not exists (select 1 from information_schema.tables where table_name='client_files')
    then raise exception 'client_files was not created'; end if;
  if exists (
    select 1 from information_schema.role_table_grants
    where table_name='client_files' and grantee in ('anon','authenticated')
  ) then raise exception 'anon or authenticated still holds a grant on client_files'; end if;
end $$;

commit;

-- ============================================================================
-- ---- 4. THE PART THAT IS NOT SQL, AND MUST NOT BE SKIPPED -----------------
--
--   a) Add ['client_files','client file'] to JV_CLIENT_TABLES in index.html.
--      Without it, deleting a client leaves their file — red lines and all —
--      in the database forever. _jvDeleteRows also falls back to an anon
--      client_code DELETE for any table with no *DeleteAll door op, and anon
--      has no grant here, so the delete would fail SILENTLY. Give it a door op.
--
--   b) Add a clientFiles read op to netlify/functions/trainer.js:
--        clientFiles: (a) => `client_files?client_code=eq.${enc(a.code)}`
--                            + `&select=*&order=created_at.desc&limit=50`
--      and a write op for the insert. Then repoint cfLoad and cfSave at them.
--
--   c) Backfill: every [FILE] row already in client_notes becomes a
--      client_files row. cfParse/_cfFromNote already read those rows, so the
--      backfill is a loop over them, not a re-parse of any paste.
--
--   d) LEAVE THE client_notes ROWS WHERE THEY ARE until (c) is verified by
--      reading the new rows back and comparing all ten fields. The interim
--      store is the backup until the new one is proven.
--
--   e) scripts/tests/tcfile.cjs must go green against the new path before the
--      old one is retired. Its assertions are storage-shaped, not table-shaped,
--      so most of them carry over unchanged.
-- ============================================================================
